; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

; Upload and Debug options
upload_protocol = stlink  ; lựa chọn giao thức nạp phù hợp với bo mạch : stlink 
debug_tool = stlink ; lựa chọn công cụ debug phù hợp với bo mạch : stlink
monitor_speed = 115200 ; tốc độ baud rate cho Serial Monitor
; board_build.ldscript = STM32F103C8TX_FLASH.ld
; FreeRTOS có sẵn trong stm32cube, kích hoạt bằng middleware
board_build.middleware = freertos
 
build_flags = 
    ; Chỉ đường dẫn đến thư mục chứa FreeRTOS.h
    -Ilib/Middlewares/Third_Party/FreeRTOS/Source/include
    ; Chỉ đường dẫn đến file cấu hình port
    -Ilib/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3

build_src_filter = +<*> +<../lib/Middlewares/Third_Party/FreeRTOS/Source/*.c> +<../lib/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/*.c> +<../lib/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>
